name: Deploy Edge Function

on:
  push:
    branches: [main] # Or your primary branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Function
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy join-waitlist --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}